spring:
  application:
    name: infinite-recipe-book
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/infinite_recipe_book
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Logging Configuration
logging:
  level:
    com.infiniterecipebook: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: Infinite Recipe Book API
    description: Intelligent recipe generation based on available ingredients
    version: 1.0.0
    contact:
      name: Infinite Recipe Book Team
      email: support@infiniterecipebook.com

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 